// <auto-generated />
using ECommerce.ProductService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.ProductService.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20260530031734_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.Shared.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Intelligent Concrete Bacon",
                            Price = 329.17m,
                            Quantity = 53
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fantastic Rubber Chips",
                            Price = 377.24m,
                            Quantity = 134
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sleek Cotton Towels",
                            Price = 467.79m,
                            Quantity = 140
                        },
                        new
                        {
                            Id = 4,
                            Name = "Unbranded Concrete Sausages",
                            Price = 238.14m,
                            Quantity = 22
                        },
                        new
                        {
                            Id = 5,
                            Name = "Gorgeous Rubber Table",
                            Price = 314.31m,
                            Quantity = 118
                        },
                        new
                        {
                            Id = 6,
                            Name = "Handmade Steel Shoes",
                            Price = 109.04m,
                            Quantity = 117
                        },
                        new
                        {
                            Id = 7,
                            Name = "Awesome Rubber Bike",
                            Price = 320.22m,
                            Quantity = 113
                        },
                        new
                        {
                            Id = 8,
                            Name = "Unbranded Rubber Chair",
                            Price = 38.82m,
                            Quantity = 76
                        },
                        new
                        {
                            Id = 9,
                            Name = "Gorgeous Concrete Keyboard",
                            Price = 51.63m,
                            Quantity = 101
                        },
                        new
                        {
                            Id = 10,
                            Name = "Refined Plastic Cheese",
                            Price = 197.41m,
                            Quantity = 48
                        },
                        new
                        {
                            Id = 11,
                            Name = "Handmade Granite Chicken",
                            Price = 215.68m,
                            Quantity = 55
                        },
                        new
                        {
                            Id = 12,
                            Name = "Sleek Rubber Tuna",
                            Price = 281.26m,
                            Quantity = 80
                        },
                        new
                        {
                            Id = 13,
                            Name = "Handcrafted Granite Mouse",
                            Price = 289.10m,
                            Quantity = 141
                        },
                        new
                        {
                            Id = 14,
                            Name = "Refined Frozen Gloves",
                            Price = 306.47m,
                            Quantity = 85
                        },
                        new
                        {
                            Id = 15,
                            Name = "Refined Concrete Pants",
                            Price = 104.49m,
                            Quantity = 47
                        },
                        new
                        {
                            Id = 16,
                            Name = "Handmade Wooden Gloves",
                            Price = 162.89m,
                            Quantity = 141
                        },
                        new
                        {
                            Id = 17,
                            Name = "Practical Steel Bike",
                            Price = 218.32m,
                            Quantity = 142
                        },
                        new
                        {
                            Id = 18,
                            Name = "Intelligent Steel Sausages",
                            Price = 462.73m,
                            Quantity = 93
                        },
                        new
                        {
                            Id = 19,
                            Name = "Handcrafted Rubber Car",
                            Price = 22.96m,
                            Quantity = 47
                        },
                        new
                        {
                            Id = 20,
                            Name = "Licensed Granite Shirt",
                            Price = 146.48m,
                            Quantity = 94
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
