// <auto-generated />
using ECommerce.ProductService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.ProductService.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.Shared.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Intelligent Wooden Gloves",
                            Price = 466.02m,
                            Quantity = 127
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tasty Frozen Mouse",
                            Price = 196.46m,
                            Quantity = 45
                        },
                        new
                        {
                            Id = 3,
                            Name = "Incredible Plastic Cheese",
                            Price = 30.15m,
                            Quantity = 127
                        },
                        new
                        {
                            Id = 4,
                            Name = "Small Fresh Sausages",
                            Price = 435.79m,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Practical Fresh Sausages",
                            Price = 58.49m,
                            Quantity = 111
                        },
                        new
                        {
                            Id = 6,
                            Name = "Practical Cotton Computer",
                            Price = 422.58m,
                            Quantity = 128
                        },
                        new
                        {
                            Id = 7,
                            Name = "Licensed Rubber Sausages",
                            Price = 256.44m,
                            Quantity = 75
                        },
                        new
                        {
                            Id = 8,
                            Name = "Handmade Granite Towels",
                            Price = 156.94m,
                            Quantity = 17
                        },
                        new
                        {
                            Id = 9,
                            Name = "Unbranded Wooden Car",
                            Price = 288.99m,
                            Quantity = 124
                        },
                        new
                        {
                            Id = 10,
                            Name = "Intelligent Concrete Shirt",
                            Price = 382.84m,
                            Quantity = 140
                        },
                        new
                        {
                            Id = 11,
                            Name = "Handmade Plastic Gloves",
                            Price = 436.07m,
                            Quantity = 136
                        },
                        new
                        {
                            Id = 12,
                            Name = "Incredible Wooden Mouse",
                            Price = 102.90m,
                            Quantity = 58
                        },
                        new
                        {
                            Id = 13,
                            Name = "Sleek Fresh Pants",
                            Price = 272.25m,
                            Quantity = 78
                        },
                        new
                        {
                            Id = 14,
                            Name = "Handcrafted Plastic Bike",
                            Price = 280.36m,
                            Quantity = 21
                        },
                        new
                        {
                            Id = 15,
                            Name = "Sleek Plastic Tuna",
                            Price = 381.26m,
                            Quantity = 14
                        },
                        new
                        {
                            Id = 16,
                            Name = "Incredible Soft Shirt",
                            Price = 146.80m,
                            Quantity = 79
                        },
                        new
                        {
                            Id = 17,
                            Name = "Gorgeous Steel Pants",
                            Price = 456.35m,
                            Quantity = 16
                        },
                        new
                        {
                            Id = 18,
                            Name = "Sleek Plastic Car",
                            Price = 304.97m,
                            Quantity = 23
                        },
                        new
                        {
                            Id = 19,
                            Name = "Awesome Plastic Pants",
                            Price = 463.59m,
                            Quantity = 89
                        },
                        new
                        {
                            Id = 20,
                            Name = "Ergonomic Soft Hat",
                            Price = 33.49m,
                            Quantity = 23
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
